### PR TITLE
added projective wall of mRICH modules

### PR DESCRIPTION
**Pull request by msar15**
In addition adding projective wall of mRICH modules- I also changed the holder box material and its thickness as well as thickness of the foam holder

### CODE REVIEW

**Comment by cdean-github** [comment]
Hi @msar15 I looked over the code and it's looking good to me. I had one question on PHG4mRICHDetector.cc line 218 (https://github.com/msar15/fun4all_eicdetectors/blob/G4_mRich/simulation/g4simulation/g4mrich/PHG4mRICHDetector.cc#L218).

Is it expected to fix  `G4int lens_type = 5;` at compilation? This doesn't allow the execution of the rest of the logic blocks without recompiling, I just wondered if this is easier to set from a user function

**Comment by cdean-github** [comment]
Hi @blackcathj do we have a preference for how to name the include folder here? 

Currently it is `g4mrich` which I'm happy with but do we want `eicg4mrich` to distinguish it?

**Comment by msar15** [comment]
> Hi @msar15 I looked over the code and it's looking good to me. I had one question on PHG4mRICHDetector.cc line 218 (https://github.com/msar15/fun4all_eicdetectors/blob/G4_mRich/simulation/g4simulation/g4mrich/PHG4mRICHDetector.cc#L218).
> 
> Is it expected to fix `G4int lens_type = 5;` at compilation? This doesn't allow the execution of the rest of the logic blocks without recompiling, I just wondered if this is easier to set from a user function

The other options were just testing cases in the very early development stage so it's expected for this not to change moving forward.

**Comment by cdean-github** [comment]
> > Hi @msar15 I looked over the code and it's looking good to me. I had one question on PHG4mRICHDetector.cc line 218 (https://github.com/msar15/fun4all_eicdetectors/blob/G4_mRich/simulation/g4simulation/g4mrich/PHG4mRICHDetector.cc#L218).
> > Is it expected to fix `G4int lens_type = 5;` at compilation? This doesn't allow the execution of the rest of the logic blocks without recompiling, I just wondered if this is easier to set from a user function
> 
> The other options were just testing cases in the very early development stage so it's expected for this not to change moving forward.

Ok, thanks for the clarification

**Pull request merged**
