### PR TITLE
Calorimetry kV3 clustering

### PR DESCRIPTION
**Pull request by tlprotzman**
Implementation of kV3 clustering algorithm

### CODE REVIEW

**Comment by cdean-github** [comment]
Hi @tlprotzman,

Thanks for putting together the clustering. I'm going through the code just now and have a question. In ```RawClusterBuilderV3.h```, you have a stuct but in the ```.cc``` file one of the members are unused. Should we remove this or set it to 0 or -1?

```c++
typedef struct
{
  float tower_E;
  int tower_iEta;
  int tower_iPhi;
  int tower_iL; // This is unused
  int tower_trueID;
  RawTower *twr;
} towersStrct;
```

```c++
      towersStrct tempTower;
      tempTower.tower_E = tower->get_energy();
      tempTower.tower_iEta = tower->get_bineta();
      tempTower.tower_iPhi = tower->get_binphi();
      tempTower.tower_trueID = towerid;  // currently unsigned -> signed, will this matter?
      tempTower.twr = itr->second;
      ```

**Comment by tlprotzman** [comment]
Hi @cdean-github, 

Good catch - I copied that struct from the existing clustering code [here](https://github.com/FriederikeBock/AnalysisSoftwareEIC/tree/master/treeAnalysis) which covers many different clustering algorithms, but `tower_iL`  isn't used in V3.  I'm not entirely clear what the parameter is, but it is used in MA clustering.  

My thought was once I get MA clustering working, I'd do a little work on the structure to avoid having the same code in multiple places, but for now it is safe to remove that from the struct.

**Comment by cdean-github** [comment]
Hi @tlprotzman,

I was able to run the code through integration checks and am happy to merge this after one final question, ```EICCaloReco.[h/cc]``` are unused here. Should these files be removed or is a push missing on them?

**Comment by tlprotzman** [comment]
Hi @cdean-github,

I believe those files were created when I was setting up the project with @blackcathj.  If there's no reason for them to exists for project structure or other reasons I am happy to delete them.

**Pull request merged**
